---
- name: "Create Directory | {{ ssl_certificate_path }}"
  file:
    path: "{{ ssl_certificate_path }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    state: directory
    mode: 0755
  tags:
    - ssl-certificate

- name: Generate Self-Signed Certificate
  command: "openssl req -newkey {{ ssl_certificate_self_options }} -x509 -subj \"{{ ssl_certificate_self_subject }}\" -days {{ ssl_certificate_self_age }} -keyout {{ ssl_certificate_path_private }} -out {{ ssl_certificate_path_public }} -extensions v3_ca"
  args:
    creates: "{{ ssl_certificate_path_public }}"
  when: ssl_certificate_self_signed
  notify: Upload Combined Public/Private Key (Self-Signed)
  tags:
    - ssl-certificate

- name: Set chmod on private key
  file: 
    path: "{{ ssl_certificate_path_private }}" 
    mode: "0440" 
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
  when: ssl_certificate_self_signed
  notify: Upload Combined Public/Private Key (Self-Signed)
  tags:
    - ssl-certificate

- name: Upload Public Certificate
  template:
    src: template.certificate
    dest: "{{ ssl_certificate_path_public }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0440
  when: not ssl_certificate_self_signed
  tags:
    - ssl-certificate

- name: Upload Private Key
  template:
    src: template.key
    dest: "{{ ssl_certificate_path_private }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0440
  when: not ssl_certificate_self_signed
  tags:
    - ssl-certificate

- name: Upload Combined Public/Private Key (not Self-Signed)
  template:
    src: template.combined
    dest: "{{ ssl_certificate_path_combined }}"
    owner: "{{ ssl_certificate_owner }}"
    group: "{{ ssl_certificate_group }}"
    mode: 0440
  when: ssl_certificate_combined and not ssl_certificate_self_signed
  tags:
    - ssl-certificate
